import {Geist_Mono, JetBrains_Mono,Inter,Nunito } from "next/font/google";
import "./globals.css";
import  LayoutWrapper  from "./LayoutWrapper";

const nunito=Nunito({
  variable:"--font-nunito",
  subsets:['latin']
})
const jetbrains = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

  const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jetbrains.variable} ${nunito.variable} ${inter.variable} ${geistMono.variable} antialiased`}
      >
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
